language: python

dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_script:
  - pip install coveralls pytest

install:
  - pip install .

script:
  - coverage run -m pytest

after_success:
  - coveralls
