language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - pip install coveralls
  - coverage run --source eventb_to_txt -m pytest
  - coverage report -m
  - pip install .

after_success:
  - coveralls
